### ISSUE TITLE
Change to `gettime` in `activity` package

### ISSUE THREAD

**Issue by erex** [distanceexamples/Distance-cameratraps#1]
Running the duiker analysis for the first time in >1year. Found the code fell over with this code

```
library(activity)
trigger.events$rtime <- gettime(trigger.events$datetime, "%Y/%m/%d %H:%M")
```

because of missing `scale` argument.

Checking documentation for `activity` package, I discover arguments `tryFormats` and `scale`. When call to `gettime` is changed to below

```
trigger.events$rtime <- gettime(trigger.events$datetime, tryFormats = "%Y/%m/%d %H:%M", scale="radian")
```

all is well. 

My question @lenthomas, did this cause a problem in April 2023 CTDS workshop, because the `activity` package was most recently updated in March 2023? If it didn't create a problem during workshop, then why now?

**Comment by lenthomas** [comment]
I updated it in the workshop exercise material, but forgot about the online example.

**Comment by erex** [comment]
I'll put it on my `todo` list courtesy of this issue

**Comment by erex** [comment]
new version of html, rmd and R code uploaded with `gettime` argument fix
